/**
 * MINI Cooper R50'ye ÖZEL arıza kodu tablosu.
 *
 * Kaynak: aracın kendi fabrika servis dokümantasyonundaki "Cooper DTCs from
 * 1/11/2003" tablosu — yani 2006 model bir R50'nin ECU'sunun gerçekten
 * kurabildiği kod listesi. Jenerik SAE tablosunun aksine burada:
 *
 *   1. **P1xxx üretici-özel kodlar var.** Jenerik tablolar bunlara "açıklama
 *      yok" der; oysa R50'de teşhis için en değerli kodların çoğu bu aralıkta:
 *      DISA değişken emme manifoldu, ikincil hava enjeksiyonu, DM-TL tank
 *      kaçak testi, elektronik gaz kelebeği adaptasyonu, eksantrik aktüatörü.
 *
 *   2. **MINI fault code (FC) numarası var.** Bayi/servis cihazları kodu
 *      P-code yerine bu numarayla gösterir. Servisle konuşurken ya da eski
 *      bir kayıtla karşılaştırırken doğrudan karşılığı bu.
 *
 * NOT: Tablo üretim tarihine göre değişiyor; burada 1/11/2003 sonrası sürüm
 * var (2006 model bunu kapsıyor). Daha eski bir R50 farklı tablo kullanır —
 * o zaman üretim tarihine göre seçim eklenmeli.
 */

export interface MiniDtcEntry {
  /** MINI/BMW'nin kendi fault code numarası (servis cihazlarında görünen). */
  readonly fc: string | null;
  readonly text: string;
}

const MINI_R50_DTCS: Readonly<Record<string, MiniDtcEntry>> = {
  P0030: { fc: '48', text: 'HO2S Heater Control Circuit (Bank 1 Sensor 1)' },
  P0031: { fc: '49', text: 'HO2S Heater Control Circuit Low (Bank 1 Sensor 1)' },
  P0032: { fc: '50', text: 'HO2S Heater Control Circuit High (Bank 1 Sensor 1)' },
  P0036: { fc: '54', text: 'HO2S Heater Control Circuit (Bank 1 Sensor 2)' },
  P0037: { fc: '55', text: 'HO2S Heater Control Circuit Low (Bank 1 Sensor 2)' },
  P0038: { fc: '56', text: 'HO2S Heater Control Circuit High (Bank 1 Sensor 2)' },
  P0053: { fc: '83', text: 'HO2S Heater Resistance (Bank 1 Sensor 1)' },
  P0054: { fc: '84', text: 'HO2S Heater Resistance (Bank 1 Sensor 2)' },
  P0101: { fc: null, text: 'Mass or Volume Air Flow Circuit Range/Performance' },
  P0102: { fc: null, text: 'Mass or Volume Air Flow Circuit Low Input' },
  P0103: { fc: null, text: 'Mass or Volume Air Flow Circuit High Input' },
  P0107: { fc: '263', text: 'Manifold Absolute Pressure/Barometric Pressure Circuit Low Input' },
  P0108: { fc: '264', text: 'Manifold Absolute Pressure/Barometric Pressure Circuit High Input' },
  P0111: { fc: null, text: 'Intake Air Temperature Range/Performance' },
  P0112: { fc: '274', text: 'Intake Air Temperature Sensor 1 Circuit Low' },
  P0113: { fc: '275', text: 'Intake Air Temperature Sensor 1 Circuit High' },
  P0114: { fc: '276', text: 'Intake Air Temperature Sensor 1 Circuit Intermittent' },
  P0116: { fc: '278', text: 'Engine Coolant Temperature Circuit Range/Performance' },
  P0117: { fc: '279', text: 'Engine Coolant Temperature Circuit Low' },
  P0118: { fc: '280', text: 'Engine Coolant Temperature Circuit High' },
  P0119: { fc: '281', text: 'Engine Coolant Temperature Circuit Intermittent' },
  P0121: { fc: null, text: 'Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance' },
  P0122: { fc: '290', text: 'Throttle/Pedal Position Sensor/Switch A Circuit Low' },
  P0123: { fc: '291', text: 'Throttle/Pedal Position Sensor/Switch A Circuit High' },
  P0125: { fc: '293', text: 'Insufficient Coolant Temperature for Closed Loop Fuel Control' },
  P0128: {
    fc: '296',
    text: 'Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)',
  },
  P0130: { fc: '304', text: 'O2 Sensor Circuit (Bank 1 Sensor 1)' },
  P0131: { fc: '305', text: 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)' },
  P0132: { fc: '306', text: 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)' },
  P0133: { fc: '307', text: 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)' },
  P0134: { fc: null, text: 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)' },
  P0135: { fc: null, text: 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)' },
  P0136: { fc: '310', text: 'O2 Sensor Circuit (Bank 1 Sensor 2)' },
  P0137: { fc: '311', text: 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)' },
  P0138: { fc: '312', text: 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)' },
  P0139: { fc: null, text: 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)' },
  P0141: { fc: null, text: 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)' },
  P0170: { fc: null, text: 'Fuel Trim Malfunction (Bank 1)' },
  P0171: { fc: '369', text: 'System Too Lean (Bank 1)' },
  P0172: { fc: '370', text: 'System Too Rich (Bank 1)' },
  P0201: { fc: '513', text: 'Injector Circuit/Open - Cylinder 1' },
  P0202: { fc: '514', text: 'Injector Circuit/Open - Cylinder 2' },
  P0203: { fc: '515', text: 'Injector Circuit/Open - Cylinder 3' },
  P0204: { fc: '516', text: 'Injector Circuit/Open - Cylinder 4' },
  P0221: { fc: null, text: 'Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance' },
  P0222: { fc: '546', text: 'Throttle/Pedal Position Sensor/Switch B Circuit Low' },
  P0223: { fc: '547', text: 'Throttle/Pedal Position Sensor/Switch B Circuit High' },
  P0261: { fc: '609', text: 'Cylinder 1 Injector Circuit Low' },
  P0262: { fc: '610', text: 'Cylinder 1 Injector Circuit High' },
  P0264: { fc: '612', text: 'Cylinder 2 Injector Circuit Low' },
  P0265: { fc: '613', text: 'Cylinder 2 Injector Circuit High' },
  P0267: { fc: '615', text: 'Cylinder 3 Injector Circuit Low' },
  P0268: { fc: '616', text: 'Cylinder 3 Injector Circuit High' },
  P0270: { fc: '624', text: 'Cylinder 4 Injector Circuit Low' },
  P0271: { fc: '625', text: 'Cylinder 4 Injector Circuit High' },
  P0300: { fc: '768', text: 'Random/Multiple Cylinder Misfire Detected' },
  P0301: { fc: '769', text: 'Cylinder 1 Misfire Detected' },
  P0302: { fc: '770', text: 'Cylinder 2 Misfire Detected' },
  P0303: { fc: '771', text: 'Cylinder 3 Misfire Detected' },
  P0304: { fc: '772', text: 'Cylinder 4 Misfire Detected' },
  P0313: { fc: '787', text: 'Misfire Detected with Low Fuel' },
  P0324: { fc: '804', text: 'Knock Control System Error' },
  P0325: { fc: null, text: 'Knock Sensor 1 Circuit, Electrical Fault in Circuit' },
  P0326: { fc: '806', text: 'Knock Sensor 1 Circuit Range/Performance' },
  P0335: { fc: '821', text: 'Crankshaft Position Sensor A Circuit' },
  P0336: { fc: '822', text: 'Crankshaft Position Sensor A Circuit Range/Performance' },
  P0339: { fc: null, text: 'Crankshaft Position Sensor A Circuit Intermittent' },
  P0340: { fc: '832', text: 'Camshaft Position Sensor A Circuit (Bank 1 or Single Sensor)' },
  P0341: {
    fc: '833',
    text: 'Camshaft Position Sensor A Circuit Range/Performance (Bank 1 or Single Sensor)',
  },
  P0344: {
    fc: null,
    text: 'Camshaft Position Sensor A Circuit Intermittent (Bank 1 or Single Sensor)',
  },
  P0365: { fc: null, text: 'Camshaft Position Sensor B Circuit Malfunction (Bank 1)' },
  P0369: { fc: null, text: 'Camshaft Position Sensor Exhaust Cam Malfunction' },
  P0412: { fc: null, text: 'Secondary Air Injection System Switching Valve Malfunction' },
  P0413: { fc: null, text: 'Secondary Air Injection System Switching Valve A Circuit Open' },
  P0414: { fc: null, text: 'Secondary Air Injection System Switching Valve A Circuit Shorted' },
  P0420: { fc: '1056', text: 'Catalyst System Efficiency Below Threshold (Bank 1)' },
  P0441: { fc: '1089', text: 'Evaporative Emission System Incorrect Purge Flow' },
  P0442: { fc: '1090', text: 'Evaporative Emission System Leak Detected (small leak)' },
  P0443: { fc: '1091', text: 'Evaporative Emission System Purge Control Valve Circuit' },
  P0444: { fc: '1092', text: 'Evaporative Emission System Purge Control Valve Circuit Open' },
  P0445: { fc: '1093', text: 'Evaporative Emission System Purge Control Valve Circuit Shorted' },
  P0455: { fc: '1109', text: 'Evaporative Emission System Leak Detected (large leak)' },
  P0456: { fc: '1110', text: 'Evaporative Emission System Leak Detected (very small leak)' },
  P0491: { fc: null, text: 'Secondary Air Injection System Insufficient Flow (Bank 1)' },
  P0500: { fc: '1280', text: 'Vehicle Speed Sensor' },
  P0505: { fc: null, text: 'Idle Control System Malfunction - Idle Speed not Plausible' },
  P0506: { fc: '1286', text: 'Idle Air Control System RPM Lower Than Expected' },
  P0507: { fc: '1287', text: 'Idle Air Control System RPM Higher Than Expected' },
  P0600: { fc: null, text: 'Serial Communication Link (Data Bus) Message Missing' },
  P0601: { fc: '1537', text: 'Internal Control Module Memory Check Sum Error' },
  P0603: { fc: '1539', text: 'Internal Control Module Keep Alive Memory (KAM) Error' },
  P0604: { fc: '1540', text: 'Internal Control Module Random Access Memory (RAM) Error' },
  P0638: { fc: '1592', text: 'Throttle Actuator Control Range/Performance (Bank 1)' },
  P0642: { fc: '1602', text: 'Sensor Reference Voltage A Circuit Low' },
  P0643: { fc: '1603', text: 'Sensor Reference Voltage A Circuit High' },
  P0652: { fc: '1618', text: 'Sensor Reference Voltage B Circuit Low' },
  P0653: { fc: '1619', text: 'Sensor Reference Voltage B Circuit High' },
  P0705: { fc: '1797', text: 'Transmission Range Sensor A Circuit Malfunction (PRNDL Input)' },
  P0815: { fc: '2069', text: 'Upshift Switch Circuit' },
  P0816: { fc: '2070', text: 'Downshift Switch Circuit' },
  P1083: { fc: null, text: 'Fuel Control Limit Mixture Too Lean (Bank 1 Sensor 1)' },
  P1084: { fc: null, text: 'Fuel Control Limit Mixture Too Rich (Bank 1 Sensor 1)' },
  P1087: { fc: null, text: 'O2 Sensor Circuit Slow Response in Lean Control Range (Bank 1 Sensor 1)' },
  P1088: { fc: null, text: 'O2 Sensor Circuit Slow Response in Rich Control Range (Bank 1 Sensor 1)' },
  P1089: { fc: null, text: 'O2 Sensor Circuit Slow Response in Lean Control Range (Bank 1 Sensor 2)' },
  P1090: { fc: null, text: 'Pre Catalyst Fuel Trim Control Too Lean (Bank 1)' },
  P1092: { fc: null, text: 'Pre Catalyst Fuel Trim Control Too Rich (Bank 1)' },
  P1106: { fc: '4358', text: 'Manifold Air Pressure Sensor Too Low at Engine Stop' },
  P1107: { fc: '4359', text: 'Manifold Air Pressure Sensor Too Low at Idle Engine Running' },
  P1108: { fc: '4360', text: 'Manifold Air Pressure Sensor Too Low at Full Load for Low Engine Speed' },
  P1109: { fc: '4361', text: 'Manifold Air Pressure Too High in Deceleration' },
  P1111: { fc: null, text: 'Engine Coolant Temperature Sensor Radiator Outlet Low Input' },
  P1112: { fc: null, text: 'Engine Coolant Temperature Sensor Radiator Outlet High Input' },
  P1120: { fc: null, text: 'Pedal Position Sensor Circuit' },
  P1121: { fc: null, text: 'Pedal Position Sensor 1 Range/Performance Problem' },
  P1122: { fc: null, text: 'Pedal Position Sensor 1 Low Input' },
  P1123: { fc: null, text: 'Pedal Position Sensor 1 High Input' },
  P1125: { fc: '4389', text: 'Throttle Position Sensor A and B Range/Performance Small Error' },
  P1126: { fc: '4390', text: 'Throttle Position Sensor A and B Range/Performance Large Error' },
  P1134: { fc: null, text: 'O2 Sensor Heater Circuit Signal Intermittent (Bank 1 Sensor 1)' },
  P1135: { fc: null, text: 'O2 Sensor Heater Circuit Low Voltage (Bank 1 Sensor 1)' },
  P1136: { fc: null, text: 'O2 Sensor Heater Circuit High Voltage (Bank 1 Sensor 1)' },
  P1137: { fc: null, text: 'O2 Sensor Heater Circuit Signal Intermittent (Bank 1 Sensor 2)' },
  P1138: { fc: null, text: 'O2 Sensor Heater Circuit Low Voltage (Bank 1 Sensor 2)' },
  P1139: { fc: null, text: 'O2 Sensor Heater Circuit High Voltage (Bank 1 Sensor 2)' },
  P1143: { fc: null, text: 'O2 Sensor Activity Check Signal Too High (Bank 1 Sensor 2)' },
  P1144: { fc: null, text: 'O2 Sensor Activity Check Signal Too Low (Bank 1 Sensor 2)' },
  P1171: { fc: null, text: 'Ambient Pressure Sensor Variant Recognition Value in Boost Range Implausible' },
  P1172: { fc: null, text: 'Ambient Pressure Sensor Variant Recognition Error Value Stored in Boot Range' },
  P1173: { fc: null, text: 'Ambient Pressure Sensor Variant Recognition Learning Failed' },
  P1178: { fc: null, text: 'O2 Sensor Pre Cat (Bank 1) - Switching Time Too Slow' },
  P1188: { fc: null, text: 'Fuel Trim (Bank 1), O2 Control Adaptation Limit - Multiplicative' },
  P1190: { fc: null, text: 'Pre Catalyst Fuel Trim Control (Bank 1)' },
  P1192: { fc: null, text: 'Post Catalyst Fuel Trim System (Bank 1)' },
  P1222: { fc: null, text: 'Pedal Position Sensor 2 Low Input' },
  P1223: { fc: null, text: 'Pedal Position Sensor 2 High Input' },
  P1229: { fc: '4649', text: 'Throttle Sensor Adaptation Failure' },
  P1314: { fc: null, text: 'Fuel Mixture Deviation Detected with Low Fuel' },
  P1320: { fc: '4896', text: 'Flywheel Adaptation for Misfire Detection Range' },
  P1321: { fc: '4897', text: 'Flywheel Adaptation for Misfire Detection Performance' },
  P1342: { fc: null, text: 'Misfire During Start Cylinder 1' },
  P1343: { fc: null, text: 'Misfire Cylinder 1 with Fuel Cut-Off' },
  P1344: { fc: null, text: 'Misfire During Start Cylinder 2' },
  P1345: { fc: null, text: 'Misfire Cylinder 2 with Fuel Cut-Off' },
  P1346: { fc: null, text: 'Misfire During Start Cylinder 3' },
  P1347: { fc: null, text: 'Misfire Cylinder 3 with Fuel Cut-Off' },
  P1348: { fc: null, text: 'Misfire During Start Cylinder 4' },
  P1349: { fc: null, text: 'Misfire Cylinder 4 with Fuel Cut-Off' },
  P1403: { fc: null, text: 'ECU internal test' },
  P1413: { fc: null, text: 'Secondary Air Injection Pump Relay Control Circuit Signal Low' },
  P1414: { fc: null, text: 'Secondary Air Injection Pump Relay Control Circuit Signal High' },
  P1423: { fc: null, text: 'Secondary Air Injection (Bank 1) - Flow too Low' },
  P1444: { fc: null, text: 'Diagnostic Module Tank Leakage (DM-TL) Pump Control Open Circuit' },
  P1445: { fc: null, text: 'Diagnostic Module Tank Leakage (DM-TL) Pump Control Circuit Signal Low' },
  P1446: { fc: null, text: 'Diagnostic Module Tank Leakage (DM-TL) Pump Control Circuit Signal High' },
  P1447: {
    fc: null,
    text: 'Diagnostic Module Tank Leakage (DM-TL) Pump Control Current Too High during Switching Solenoid Test',
  },
  P1448: { fc: null, text: 'Diagnostic Module Tank Leakage (DM-TL) Pump Current Too Low' },
  P1449: { fc: null, text: 'Diagnostic Module Tank Leakage (DM-TL) Pump Current Too High' },
  P1451: {
    fc: null,
    text: 'Diagnostic Module Tank Leakage (DM-TL) Switching Solenoid Control Circuit Signal Low',
  },
  P1452: {
    fc: null,
    text: 'Diagnostic Module Tank Leakage (DM-TL) Switching Solenoid Control Circuit Signal High',
  },
  P1453: { fc: null, text: 'Secondary Air Injection System - Relay or Pump' },
  P1475: { fc: '5237', text: 'Leakage Diagnostic Pump Reed Switch Did not Close' },
  P1476: { fc: '5238', text: 'Leakage Diagnostic Pump Clamped Tube' },
  P1477: { fc: '5239', text: 'Leakage Diagnostic Pump Reed Switch Did Not Open' },
  P1478: { fc: null, text: 'Range Check Voltage Supply Pedal Sensor 1 and Throttle Position Sensors' },
  P1500: { fc: null, text: 'Idle Speed Control Valve Stuck Open' },
  P1501: { fc: null, text: 'Idle Speed Control Valve Stuck Closed' },
  P1502: { fc: null, text: 'Idle Speed Control Valve Closing Solenoid Control Circuit Signal High' },
  P1503: { fc: null, text: 'Idle Speed Control Valve Closing Solenoid Control Circuit Signal Low' },
  P1504: { fc: null, text: 'Idle Speed Control Valve Closing Solenoid Control Open Circuit' },
  P1506: { fc: null, text: 'Idle Speed Control Valve Opening Solenoid Control Circuit Signal High' },
  P1507: { fc: null, text: 'Idle Speed Control Valve Opening Solenoid Control Circuit Signal Low' },
  P1508: { fc: null, text: 'Idle Speed Control Valve Opening Solenoid Control Open Circuit' },
  P1509: { fc: null, text: 'Idle Control Valve Opening Coil - Malfunction' },
  P1512: { fc: null, text: 'DISA (Differentiated Intake Manifold) Control Circuit Signal Low' },
  P1513: { fc: null, text: 'DISA (Differentiated Intake Manifold) Control Circuit Signal High' },
  P1523: { fc: null, text: 'A Camshaft Position Actuator Signal Low (Bank 1)' },
  P1524: { fc: null, text: 'A Camshaft Position Actuator Control Circuit Signal High (Bank 1)' },
  P1529: { fc: null, text: 'B Camshaft Position Actuator Control Circuit Signal Low (Bank 1)' },
  P1530: { fc: null, text: 'B Camshaft Position Actuator Control Circuit Signal High (Bank 1)' },
  P1550: { fc: null, text: 'Idle Control Valve Closing Coil - Malfunction' },
  P1572: { fc: '5490', text: 'Electronic Control Module Sensor Supply A Noisy Signal' },
  P1575: { fc: '5493', text: 'Electronic Control Module Sensor Supply B Noisy Signal' },
  P1600: { fc: '5632', text: 'External Control Module Random Access Memory (RAM) Error' },
  P1602: { fc: null, text: 'Control Module Self Test - Control Module Defective' },
  P1603: { fc: null, text: 'Control Module Self Test - Torque Monitoring' },
  P1604: { fc: null, text: 'Control Module Self Test - Speed Monitoring' },
  P1607: { fc: '5639', text: 'CAN-Version' },
  P1611: { fc: '5649', text: 'Serial Communication Link Transmission Control Module' },
  P1612: { fc: '5650', text: 'Serial Communication Link Instrument Pack' },
  P1613: { fc: '5651', text: 'Serial Communication Link ASC (Automatic Stability Control)' },
  P1615: { fc: '5653', text: 'Electronic Control Module Processor SPI-Bus Failure' },
  P1617: { fc: '5655', text: 'Electronic Control Module H Bridge Controller' },
  P1619: { fc: null, text: 'Map Cooling Thermostat Control Circuit Signal Low' },
  P1620: { fc: null, text: 'Map Cooling Thermostat Control Circuit Signal High' },
  P1624: { fc: null, text: 'Pedal Position Sensor Potentiometer Supply Channel 1 Electrical' },
  P1625: { fc: null, text: 'Pedal Position Sensor Potentiometer Supply Channel 2 Electrical' },
  P1632: { fc: null, text: 'Throttle Valve Adaptation Conditions Not Met' },
  P1633: { fc: null, text: 'Throttle Valve Adaptation Limp-Home Positions Unknown' },
  P1634: { fc: null, text: 'Throttle Valve Adaptation Spring Test Failed' },
  P1635: { fc: null, text: 'Throttle Valve Adaptation Lower Mechanical Stop not Adapted' },
  P1636: { fc: null, text: 'Throttle Valve Control Circuit Mechanically; pulse width not plausible' },
  P1637: { fc: null, text: 'Throttle Valve Position Control, Control Deviation' },
  P1638: { fc: null, text: 'Throttle Valve Position Control Throttle Stuck Temporarily' },
  P1639: { fc: null, text: 'Throttle Valve Position Control Throttle Stuck Permanently' },
  P1675: { fc: null, text: 'Throttle Valve Actuator Start Test Re-Adaptation Required' },
  P1679: { fc: '5753', text: 'Electronic Throttle Control Monitor Level 2/3 Torque Loss Calculation' },
  P1680: { fc: '5760', text: 'Electronic Throttle Control Monitor Level 2/3 ADC Processor Fault' },
  P1681: { fc: '5761', text: 'Electronic Throttle Control Monitor Level 2/3 Engine Speed Calculation Error' },
  P1682: { fc: '5762', text: 'Electronic Throttle Control Monitor Level 2/3 Idle Speed A Calculation Fault' },
  P1683: { fc: '5763', text: 'Electronic Throttle Control Monitor Level 2/3 Idle Speed B Calculation Fault' },
  P1684: { fc: '5764', text: 'Electronic Throttle Control Monitor Level 2/3 Clutch Torque Min Error' },
  P1685: { fc: '5765', text: 'Electronic Throttle Control Monitor Level 2/3 Clutch Torque Max Error' },
  P1686: {
    fc: '5766',
    text: 'Electronic Throttle Control Monitor Level 2/3 Pedal Position Sensor Diagnostic Error',
  },
  P1687: {
    fc: '5767',
    text: 'Electronic Throttle Control Monitor Level 2/3 Throttle Position Sensor Diagnostic Error',
  },
  P1688: { fc: '5768', text: 'Electronic Throttle Control Monitor Level 2/3 Mass Air Flow Calculation' },
  P1689: { fc: '5769', text: 'Electronic Throttle Control Monitor Level 2/3 Torque Calculation Error' },
  P1691: {
    fc: '5777',
    text: 'Electronic Throttle Control Monitor Level 2/3 Motorized Throttle Control Engine Speed Limitation Error',
  },
  P1692: {
    fc: '5778',
    text: 'Electronic Throttle Control Monitor Level 2/3 Motorized Throttle Control and Fuel Injection Switch Off A',
  },
  P1693: {
    fc: '5779',
    text: 'Electronic Throttle Control Monitor Level 2/3 Motorized Throttle Control and Fuel Injection Switch Off B',
  },
  P1694: { fc: null, text: 'Throttle Valve Actuator Start Test Spring Test and Limp-Home Position Failed' },
  P1698: { fc: '5784', text: 'Transmission Control Module Control Error' },
  P1699: { fc: '5785', text: 'Transmission Control Module Checksum Error' },
  P1705: { fc: '5893', text: 'Transmission Control Module LED Output Open Circuit' },
  P1706: { fc: '5894', text: 'Transmission Control Module LED Output Short Circuit' },
  P1739: { fc: '5945', text: 'Clutch Solenoid Communication Error' },
  P1741: { fc: '5953', text: 'Clutch Solenoid Open Circuit' },
  P1742: { fc: '5954', text: 'Clutch Solenoid Short Circuit' },
  P1749: { fc: '5961', text: 'Secondary Pressure Solenoid Communication Error' },
  P1751: { fc: '5969', text: 'Secondary Pressure Solenoid Open Circuit' },
  P1752: { fc: '5970', text: 'Secondary Pressure Solenoid Short Circuit' },
  P1785: { fc: '6021', text: 'Transmission Ratio Control Actuator Circuit Malfunction' },
  P1786: { fc: '6022', text: 'Transmission Ratio Control Actuator Circuit Range/Performance' },
  P1787: { fc: '6023', text: 'Transmission Ratio Control Actuator Open Circuit' },
  P1788: { fc: '6024', text: 'Transmission Ratio Control Actuator Short Circuit' },
  P1789: { fc: '6025', text: 'Transmission Ratio Control Actuator Communication Error' },
  P1815: { fc: '6165', text: 'Wheel Plus Switch Error Low Input' },
  P1816: { fc: '6166', text: 'Wheel Minus Switch Error Low Input' },
  P2088: { fc: null, text: 'A Camshaft Position Actuator Control Circuit Low (Bank 1)' },
  P2089: { fc: null, text: 'A Camshaft Position Actuator Control Circuit High (Bank 1)' },
  P2090: { fc: null, text: 'B Camshaft Position Actuator Control Circuit Low (Bank 1)' },
  P2091: { fc: null, text: 'B Camshaft Position Actuator Control Circuit High (Bank 1)' },
  P2096: { fc: '8342', text: 'Post Catalyst Fuel Trim System Too Lean (Bank 1)' },
  P2097: { fc: '8343', text: 'Post Catalyst Fuel Trim System Too Rich (Bank 1)' },
  P2122: { fc: '8482', text: 'Throttle/Pedal Position Sensor/Switch D Circuit Low Input' },
  P2123: { fc: '8483', text: 'Throttle/Pedal Position Sensor/Switch D Circuit High Input' },
  P2127: { fc: '8487', text: 'Throttle/Pedal Position Sensor/Switch E Circuit Low Input' },
  P2128: { fc: '8488', text: 'Throttle/Pedal Position Sensor/Switch E Circuit High Input' },
  P2138: { fc: '8504', text: 'Throttle/Pedal Position Sensor/Switch D / E Voltage Correlation' },
  P2228: { fc: null, text: 'Barometric Pressure Circuit Low' },
  P2270: { fc: '8816', text: 'O2 Sensor Signal Stuck Lean (Bank 1 Sensor 2)' },
  P2271: { fc: '8817', text: 'O2 Sensor Signal Stuck Rich (Bank 1 Sensor 2)' },
  P2300: { fc: '8960', text: 'Ignition Coil A Primary Control Circuit Low' },
  P2301: { fc: '8961', text: 'Ignition Coil A Primary Control Circuit High' },
  P2303: { fc: '8963', text: 'Ignition Coil B Primary Control Circuit Low' },
  P2304: { fc: '8964', text: 'Ignition Coil B Primary Control Circuit High' },
  P2400: { fc: '9216', text: 'Evaporative Emission System Leak Detection Pump Control Circuit/Open' },
  P2401: { fc: '9217', text: 'Evaporative Emission System Leak Detection Pump Control Circuit Low' },
  P2402: { fc: '9218', text: 'Evaporative Emission System Leak Detection Pump Control Circuit High' },
  P2404: {
    fc: '9220',
    text: 'Evaporative Emission System Leak Detection Pump Sense Circuit Range/Performance',
  },
};

/** R50'ye özel kod tanımını döndürür (tabloda yoksa undefined). */
export function lookupMiniDtc(code: string): MiniDtcEntry | undefined {
  return MINI_R50_DTCS[code.toUpperCase()];
}

/** Tablodaki toplam kod sayısı — UI'da "R50 kod tablosu yüklü" göstermek için. */
export const MINI_R50_DTC_COUNT = Object.keys(MINI_R50_DTCS).length;
